// ts/codegen/host.d.ts — the host API of the self-hosted code generator.
// The generator is a TOOL: it typechecks against exactly these three host
// hooks (wired by ts/codegen/selfhost.cpp through ScriptRuntime), never
// against api/engine.d.ts — the artifact it produces cannot be its own
// compile-time dependency.

/** The engine_api.json text (raw document or `midday api dump --json` envelope). */
declare function readInput(): string;

/** Deliver one generated artifact (engine.d.ts, schema_manifest.json, api_docs.md, bindings_spec.json). */
declare function writeOutput(name: string, content: string): void;

/** Debug channel (host stderr); never part of the generated bytes. */
declare function log(...parts: string[]): void;

/** Entry point installed by generator.ts; called once per run via call_json. */
// eslint-style naming aside: the double-underscore prefix marks host-visible globals.
declare var __midday_codegen_run: ((request: unknown) => unknown) | undefined;
